let resumeData = {
  name: "Menderes Koc",
  role: "Full Stack Web Developer",
  socialLinks: [
    {
      name: "linkedin",
      url: "https://www.linkedin.com/in/mendereskoc/",
      className: "fa fa-linkedin",
    },
    {
      name: "github",
      url: "https://github.com/MenderesKoc",
      className: "fa fa-github",
    },
  ],
  portfolio: {
    projects: [
      {
        title: "Disney Platformer",
        shorttitle: "Disney Platformer",
        category: "Personal Project",
        image: "disneyPlatformer.PNG",
        info: "HTML, CSS, JS, Bootstrap, Adobe Photoshop",
        url: "https://tutchings.github.io/disneyPlatformer/",
        repo: "https://github.com/tutchings/disneyPlatformer",
      },
      {
        title: "Wake Forest University ASGM Project",
        shorttitle: "WFU ASGM Project",
        category: "Academic (group) Project",
        image: "wfu-asgm-project.PNG",
        info: "Amazon Web Services (AWS), Serverless, Express, Vuejs, Nodejs, Axios, MongoDB, Mongoose, HTML, CSS, JS, jQuery",
        url: "https://asgmwfu.com/index.html",
        repo: "https://github.com/tutchings/wfu-asgm-awsServerlessLambda",
      },
      {
        title: "Exploring National Parks During Covid: Live Search",
        shorttitle: "NPS Covid: Live Search",
        category: "Academic (group) Project",
        image: "nps.png",
        info: "HTML, CSS, JS, jQuery, Materialize, GoogleMaps and Geocoding APIs, NPS API, Covid Tracking Project API, Bing News API, MapQuest API",
        url: "https://tutchings.github.io/exploringParksDuringCovidLiveSearch/",
        repo: "https://github.com/tutchings/exploringParksDuringCovidLiveSearch",
      },
      {
        title: "React User Directory",
        shorttitle: "React User Directory",
        category: "Academic Project",
        image: "userDirectoryImg1.PNG",
        info: "React, Nodejs, Axios, Random User API, HTML, CSS, JS, Bootstrap",
        url: "https://tutchings.github.io/19-user-directory/",
        repo: "https://github.com/tutchings/19-user-directory",
      },
      {
        title: "Budget Tracker PWA",
        shorttitle: "Budget Tracker",
        category: "Academic Project",
        image: "budgetTracker1.PNG",
        info: "MongoDB, Mongoose, webpack, service-worker, Express, Nodejs",
        url: "https://budget-tracker-18-pwa.herokuapp.com",
        repo: "https://github.com/tutchings/18_BudgetTrackerPWA",
      },
      {
        title: "Burger Tracker",
        shorttitle: "Burger Tracker",
        category: "Academic Project",
        image: "burgerTracker.PNG",
        info: "MySql, Express, Nodejs, Handlebars, HTML, CSS, JS, Bootstrap, jQuery",
        url: "https://mysql-mvc-burger-shop.herokuapp.com/",
        repo: "https://github.com/tutchings/13_burgerTracker",
      },
      {
        title: "Weather Dashboard",
        shorttitle: "Weather Dashboard",
        category: "Academic Project",
        image: "weatherDashboard.png",
        info: "HTML, CSS, Bootstrap, JS, jQuery, OpenWeather API, MapQuest API",
        url: "https://tutchings.github.io/6_weatherDashboard/",
        repo: "https://github.com/tutchings/6_weatherDashboard",
      },
      {
        title: "BlackJack Game",
        shorttitle: "BlackJack",
        category: "Personal Project",
        image: "blackjack.PNG",
        info: "HTML, CSS, JS",
        url: "https://tutchings.github.io/blackjack/",
        repo: "https://github.com/tutchings/blackjack",
      },
    ],
  },
};
export default resumeData;
